//
//  Flag.swift
//  July-28
//
//  Created by Vishal Singh on 29/07/18.
//  Copyright © 2018 v-i-s-h-a-l. All rights reserved.
//

import Foundation

extension Country {
    
    var flag: String {
        switch self {
            
        // AFRICA
        case .algeria: return "🇩🇿"
        case .angola: return "🇦🇴"
        case .benin: return "🇧🇯"
        case .botswana: return "🇧🇼"
        case .burundi: return "🇧🇮"
        case .cameroon: return "🇨🇲"
        case .chad: return "🇹🇩"
        case .comoros: return "🇰🇲"
        case .djibouti: return "🇩🇯"
        case .egypt: return "🇪🇬"
        case .eritrea: return "🇪🇷"
        case .ethiopia: return "🇪🇹"
        case .gabon: return "🇬🇦"
        case .gambia: return "🇬🇲"
        case .ghana: return "🇬🇭"
        case .guinea: return "🇬🇳"
        case .kenya: return "🇰🇪"
        case .lesotho: return "🇱🇸"
        case .liberia: return "🇱🇷"
        case .libya: return "🇱🇾"
        case .madagascar: return "🇲🇬"
        case .malawi: return "🇲🇼"
        case .mali: return "🇲🇱"
        case .mauritania: return "🇲🇷"
        case .mauritius: return "🇲🇺"
        case .morocco: return "🇲🇦"
        case .mozambique: return "🇲🇿"
        case .namibia: return "🇳🇦"
        case .niger: return "🇳🇪"
        case .nigeria: return "🇳🇬"
        case .rwanda: return "🇷🇼"
        case .senegal: return "🇸🇳"
        case .seychelles: return "🇸🇨"
        case .somalia: return "🇸🇴"
        case .sudan: return "🇸🇩"
        case .tanzania: return "🇹🇿"
        case .togo: return "🇹🇬"
        case .tunisia: return "🇹🇳"
        case .uganda: return "🇺🇬"
        case .zambia: return "🇿🇲"
        case .zimbabwe: return "🇿🇼"
            
            
        // ASIA
        case .afghanistan: return "🇦🇫"
        case .armenia: return "🇦🇲"
        case .bangladesh: return "🇧🇩"
        case .bhutan: return "🇧🇹"
        case .brunei: return "🇧🇳"
        case .china: return "🇨🇳"
        case .cyprus: return "🇨🇾"
        case .georgia: return "🇬🇪"
        case .india: return "🇮🇳"
        case .indonesia: return "🇮🇩"
        case .iran: return "🇮🇷"
        case .iraq: return "🇮🇶"
        case .israel: return "🇮🇱"
        case .japan: return "🇯🇵"
        case .jordan: return "🇯🇴"
        case .kuwait: return "🇰🇼"
        case .lebanon: return "🇱🇧"
        case .malaysia: return "🇲🇾"
        case .maldives: return "🇲🇻"
        case .nepal: return "🇳🇵"
        case .pakistan: return "🇵🇰"
        case .russia: return "🇷🇺"
        case .singapore: return "🇸🇬"
        case .syria: return "🇸🇾"
        case .turkey: return "🇹🇷"
            
        // Europe
        case .albania: return "🇦🇱"
        case .andorra: return "🇦🇩"
        case .austria: return "🇦🇹"
        case .azerbaijan: return "🇦🇿"
        case .belarus: return "🇧🇾"
        case .belgium: return "🇧🇪"
        case .bulgaria: return "🇧🇬"
        case .croatia: return "🇭🇷"
        case .denmark: return "🇩🇰"
        case .england: return "🏴󠁧󠁢󠁥󠁮󠁧󠁿"
        case .estonia: return "🇪🇪"
        case .finland: return "🇫🇮"
        case .france: return "🇫🇷"
        case .germany: return "🇩🇪"
        case .greece: return "🇬🇷"
        case .hungary: return "🇭🇺"
        case .iceland: return "🇮🇸"
        case .ireland: return "🇮🇪"
        case .italy: return "🇮🇹"
        case .kazakhstan: return "🇰🇿"
        case .kosovo: return "🇽🇰"
        case .latvia: return "🇱🇻"
        case .liechtenstein: return "🇱🇮"
        case .lithuania: return "🇱🇹"
        case .luxembourg: return "🇱🇺"
        case .macedonia: return "🇲🇰"
        case .malta: return "🇲🇹"
        case .moldova: return "🇲🇩"
        case .monaco: return "🇲🇨"
        case .montenegro: return "🇲🇪"
        case .netherlands: return "🇳🇱"
        case .norway: return "🇳🇴"
        case .poland: return "🇵🇱"
        case .portugal: return "🇵🇹"
        case .romania: return "🇷🇴"
        case .scotland: return "🏴󠁧󠁢󠁳󠁣󠁴󠁿"
        case .serbia: return "🇷🇸"
        case .slovakia: return "🇸🇰"
        case .slovenia: return "🇸🇮"
        case .spain: return "🇪🇸"
        case .sweden: return "🇸🇪"
        case .switzerland: return "🇨🇭"
        case .ukraine: return "🇺🇦"
        case .wales: return "🏴󠁧󠁢󠁷󠁬󠁳󠁿"
            
        // NORTH AMERICA
        case .bahamas: return "🇧🇸"
        case .barbados: return "🇧🇧"
        case .belize: return "🇧🇿"
        case .canada: return "🇨🇦"
        case .cuba: return "🇨🇺"
        case .dominica: return "🇩🇲"
        case .guatemala: return "🇬🇹"
        case .haiti: return "🇭🇹"
        case .honduras: return "🇭🇳"
        case .jamaica: return "🇯🇲"
        case .mexico: return "🇲🇽"
        case .nicaragua: return "🇳🇮"
        case .panama: return "🇵🇦"
            
        // SOUTH AMERICA
        case .argentina: return "🇦🇷"
        case .brazil: return "🇧🇷"
        case .chile: return "🇨🇱"
        case .colombia: return "🇨🇴"
        case .ecuador: return "🇪🇨"
        case .guyana: return "🇬🇾"
        case .paraguay: return "🇵🇾"
        case .peru: return "🇵🇪"
        case .suriname: return "🇸🇷"
        case .uruguay: return "🇺🇾"
        case .venezuela: return "🇻🇪"
            
        // AUSTRALIA AND OCEANIA
        case .australia: return "🇦🇺"
        case .fiji: return "🇫🇯"
        case .kiribati: return "🇰🇮"
        case .micronesia: return "🇫🇲"
        case .nauru: return "🇳🇷"
        case .palau: return "🇵🇼"
        case .samoa: return "🇼🇸"
        case .tuvalu: return "🇹🇻"
        case .vanuatu: return "🇻🇺"
            
        }
    }
}
